### ISSUE TITLE
Move ownership to the xbmc organization?

### ISSUE THREAD

**Issue by enen92** [xbmc/kodi-addon-submitter#13]
Due to the fact we must get a way of defining a common workflow and instructions to our users (especially with all this matrix huge ammount of work), it would be cool to transfer the ownership of this project from a personal account to the `xbmc` organization.

What do you think? I did the same with my actions

**Comment by romanvm** [comment]
I don't mind. Let me check what needs to be done.

**Comment by romanvm** [comment]
Ok, finally I've got to it but my attempt transfer ownership to `xbmc` failed because I have no rights to create repos in `xbmc`.

**Comment by enen92** [comment]
Ping @yol
Can you help with this?

**Comment by yol** [comment]
Of course, can it wait until Monday? (on vacation atm)

**Comment by yol** [comment]
All set!
